### ISSUE TITLE
OnItemClickListener to get row & column no.

### ISSUE THREAD

**Issue by rhaul** [florent37/MaterialLeanBack#2]
Hi florent37,

Thanks for this awesome library but I'm having an issue with implementing the item click listener for this view. I have tried modifying the adapter but with that I am only being able to fetch either row no or column no at once. Without the click functionality it only looks like a gallery.

**Comment by Seichis** [comment]
Did you find a solution to this problem? I face the same issue.

**Comment by Shirish8893** [comment]
Hi florent37,

I am trying to implement onItemclicklistener to this so that it can open the image in full screen from the path we mentioned at viewHolder. Can you help me on this? I would really appreciate.

**Comment by Shirish8893** [comment]
Hi @rhaul 

I saw you were also trying for same. Did you find the solution bro?

**Comment by florent37** [comment]
done in the 1.0.2, 

```java
materialLeanBack.setOnItemClickListener(new MaterialLeanBack.OnItemClickListener() {
            @Override
            public void onTitleClicked(int row, String text) {
                Toast.makeText(getApplicationContext(), "onTitleClicked "+row+" "+text, Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onItemClicked(int row, int column) {
                Toast.makeText(getApplicationContext(), "onItemClicked "+row+" "+column, Toast.LENGTH_SHORT).show();
            }
        });
```
