### ISSUE TITLE
is it possible to scroll to particular card?

### ISSUE THREAD

**Issue by hiteshchavda** [florent37/MaterialLeanBack#3]
something like....
getListView().setSelection(5);
getListView().smoothScrollToPosition(5);

**Comment by florent37** [comment]
done in 1.0.2

**Comment by IncorporateApps** [comment]
this should be reopened. it does not seem to scroll consistently in a horizontal RecyclerView with one row. Particularly when you scroll a single row to the right it seems to work ok, but to the left again it will scroll and enlarge 2 positions to the right of the correct position. If you put stops or Logs into the CellViewHolder you will see that if you want to scroll to lets say pos:0,15 from pos:0,30 it will scroll all the way to 17 and stop and enlarge it.

It should go all the way down to 15. When you scroll up from pos:0,15 to pos:0,30 it seems to work fine. 

It has to do something with the way the PLACEHOLDER_START_SIZE is being subtracted and added maybe?
getAdapterPosition()-CellAdapter.PLACEHOLDER_START_SIZE
