### ISSUE TITLE
wrong row count 

### ISSUE THREAD

**Issue by a3adel** [florent37/MaterialLeanBack#6]
when trying to return one or tow rows it returns nothing
yet if i returned 3 rows it returns 1 row only 
if i returned 4 rows it returns  2 rows
it returns the rows count - 2
same for the cell count 
it returns the count - 2

**Comment by Chingiz** [comment]
Hey! I had this problem, too. Just clone the library and import in Android Studio and everything is going to work very well.

**Comment by vishalpatel1327** [comment]
change 
  compile 'com.github.florent37:materialleanback:1.0.1@aar'
insteed of 
  compile 'com.github.florent37:materialleanback:1.0.0@aar'

**Comment by florent37** [comment]
it should works now ;)

**Comment by vishalpatel1327** [comment]
hahaha
great to see you after long time. ;)
